import { type NextRequest, NextResponse } from "next/server"

// Mock movie database (same as above, but we'll import it in a real app)
const movies = [
  {
    id: 1,
    title: "Stranger Things",
    description:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    image: "/stranger-things-inspired-poster.png",
    year: "2023",
    rating: "TV-14",
    genre: ["Drama", "Fantasy", "Horror"],
    duration: "51m",
    category: "trending",
    videoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "David Harbour"],
    director: "The Duffer Brothers",
    seasons: 4,
    episodes: 34,
  },
  {
    id: 2,
    title: "The Crown",
    description:
      "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the twentieth century.",
    image: "/the-crown-inspired-poster.png",
    year: "2023",
    rating: "TV-MA",
    genre: ["Drama", "History"],
    duration: "58m",
    category: "trending",
    videoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    cast: ["Claire Foy", "Olivia Colman", "Imelda Staunton"],
    director: "Peter Morgan",
    seasons: 6,
    episodes: 60,
  },
  {
    id: 3,
    title: "Wednesday",
    description:
      "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends at Nevermore Academy.",
    image: "/wednesday-addams-poster.png",
    year: "2022",
    rating: "TV-14",
    genre: ["Comedy", "Crime", "Family"],
    duration: "45m",
    category: "trending",
    videoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    cast: ["Jenna Ortega", "Emma Myers", "Enid Sinclair"],
    director: "James Lovato",
    seasons: 1,
    episodes: 8,
  },
  {
    id: 4,
    title: "Ozark",
    description:
      "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.",
    image: "/ozark-inspired-poster.png",
    year: "2022",
    rating: "TV-MA",
    genre: ["Crime", "Drama", "Thriller"],
    duration: "60m",
    category: "trending",
    videoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    cast: ["Jason Bateman", "Laura Linney", "Sofia Hublitz"],
    director: "Bill Dubuque",
    seasons: 4,
    episodes: 44,
  },
  {
    id: 5,
    title: "The Witcher",
    description:
      "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    image: "/witcher-inspired-poster.png",
    year: "2023",
    rating: "TV-MA",
    genre: ["Action", "Adventure", "Drama"],
    duration: "60m",
    category: "trending",
    videoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    cast: ["Henry Cavill", "Anya Chalotra", "Freya Allan"],
    director: "Lauren Schmidt Hissrich",
    seasons: 3,
    episodes: 24,
  },
  {
    id: 6,
    title: "Bridgerton",
    description:
      "Wealth, lust, and betrayal set against the backdrop of Regency-era England, seen through the eyes of the powerful Bridgerton family.",
    image: "/bridgerton-inspired-poster.png",
    year: "2022",
    rating: "TV-MA",
    genre: ["Drama", "Romance"],
    duration: "60m",
    category: "trending",
    videoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    cast: ["Nicola Coughlan", "Jonathan Bailey", "Simone Ashley"],
    director: "Chris Van Dusen",
    seasons: 2,
    episodes: 16,
  },
  {
    id: 7,
    title: "Extraction",
    description:
      "A black-market mercenary who has nothing to lose is hired to rescue the kidnapped son of an imprisoned international crime lord.",
    image: "/generic-action-movie-poster.png",
    year: "2023",
    rating: "R",
    genre: ["Action", "Thriller"],
    duration: "116m",
    category: "action",
    videoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    cast: ["Chris Hemsworth", "Rudhraksh Jaiswal", "Randeep Hooda"],
    director: "Sam Hargrave",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 8,
    title: "Red Notice",
    description: "An Interpol agent tracks the world's most wanted art thief.",
    image: "/red-notice-inspired-poster.png",
    year: "2021",
    rating: "PG-13",
    genre: ["Action", "Comedy", "Thriller"],
    duration: "118m",
    category: "action",
    videoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    cast: ["Dwayne Johnson", "Ryan Reynolds", "Gal Gadot"],
    director: "Rawson Marshall Thurber",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 9,
    title: "6 Underground",
    description:
      "Six individuals from all around the globe, each the very best at what they do, have been chosen not only for their skill, but for a unique desire to delete their pasts to change the future.",
    image: "/6-underground-poster.png",
    year: "2019",
    rating: "R",
    genre: ["Action", "Thriller"],
    duration: "128m",
    category: "action",
    videoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    cast: ["Ryan Reynolds", "Mélanie Laurent", "Manju Warrier"],
    director: "Michael Bay",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 10,
    title: "The Gray Man",
    description:
      "When the CIA's most skilled operative-whose true identity is known to none-accidentally uncovers dark agency secrets, a psychopathic former colleague puts a bounty on his head.",
    image: "/the-gray-man-poster.png",
    year: "2022",
    rating: "PG-13",
    genre: ["Action", "Thriller"],
    duration: "129m",
    category: "action",
    videoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    cast: ["Ryan Gosling", "Chris Evans", "Ana de Armas"],
    director: "Anthony Russo, Joe Russo",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 11,
    title: "Army of the Dead",
    description:
      "Following a zombie outbreak in Las Vegas, a group of mercenaries take the ultimate gamble, venturing into the quarantine zone to pull off the greatest heist ever attempted.",
    image: "/army-of-the-dead-poster.png",
    year: "2021",
    rating: "R",
    genre: ["Action", "Crime", "Horror"],
    duration: "148m",
    category: "action",
    videoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    cast: ["Dave Bautista", "Ella Purnell", "Omari Hardwick"],
    director: "Zack Snyder",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 12,
    title: "Thunder Force",
    description:
      "In a world where supervillains are commonplace, two estranged childhood best friends reunite after one devises a treatment that gives them powers to protect their city.",
    image: "/thunder-force-poster.png",
    year: "2021",
    rating: "PG-13",
    genre: ["Action", "Adventure", "Comedy"],
    duration: "106m",
    category: "action",
    videoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    cast: ["Melissa McCarthy", "Octavia Spencer", "Jason Bateman"],
    director: "Ben Falcone",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 13,
    title: "Murder Mystery",
    description:
      "A New York cop and his wife go on a European vacation to reinvigorate the spark in their marriage, but end up getting framed and on the run for the death of an elderly billionaire.",
    image: "/murder-mystery-poster.png",
    year: "2023",
    rating: "PG-13",
    genre: ["Action", "Comedy", "Crime"],
    duration: "97m",
    category: "comedy",
    videoSrc: "https://www.youtube.com/embed/SubaruOutbackOnStreetAndDirt",
    cast: ["Adam Sandler", "Jennifer Aniston", "Luke Evans"],
    director: "Kyle Newacheck",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 15,
    title: "Enola Holmes",
    description:
      "When Enola Holmes-Sherlock's teen sister-discovers her mother missing, she sets off to find her, becoming a super-sleuth in her own right.",
    image: "/enola-holmes-poster.png",
    year: "2022",
    rating: "PG-13",
    genre: ["Adventure", "Crime", "Drama"],
    duration: "123m",
    category: "comedy",
    videoSrc: "https://www.youtube.com/embed/TearsOfSteel",
    cast: ["Millie Bobby Brown", "Henry Cavill", "Sam Claflin"],
    director: "Harry Bradbeer",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 16,
    title: "The Half of It",
    description: "A shy student helps the sweet jock woo the girl they both like.",
    image: "/the-half-of-it-poster.png",
    year: "2020",
    rating: "PG-13",
    genre: ["Comedy", "Drama", "Romance"],
    duration: "104m",
    category: "comedy",
    videoSrc: "https://www.youtube.com/embed/VolkswagenGTIReview",
    cast: ["Leah Lewis", "Daniel Diemer", "Alexxis Lemire"],
    director: "Alice Wu",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 17,
    title: "RRR",
    description:
      "A fearless revolutionary and an officer in the British force, who once shared a deep bond, decide to join forces and chart out an inspirational path of freedom against the despotic rule.",
    image: "/rrr-tamil-poster.png",
    year: "2022",
    rating: "PG-13",
    genre: ["Action", "Drama", "History"],
    duration: "187m",
    category: "tamil",
    videoSrc: "https://www.youtube.com/embed/f_vbAtFSEc0",
    cast: ["N. T. Rama Rao Jr.", "Ram Charan", "Alia Bhatt", "Ajay Devgn"],
    director: "S. S. Rajamouli",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 18,
    title: "Baahubali 2: The Conclusion",
    description:
      "When Shiva, the son of Bahubali, learns about his heritage, he begins to look for answers. His story is juxtaposed with past events that unfolded in the Mahishmati Kingdom.",
    image: "/baahubali-2-poster.png",
    year: "2017",
    rating: "PG-13",
    genre: ["Action", "Drama", "Fantasy"],
    duration: "167m",
    category: "tamil",
    videoSrc: "https://www.youtube.com/embed/sOEg_YZQsTI",
    cast: ["Prabhas", "Rana Daggubati", "Anushka Shetty", "Tamannaah Bhatia"],
    director: "S. S. Rajamouli",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 19,
    title: "Vikram",
    description: "Members of a black ops team must track and eliminate a gang of masked murderers.",
    image: "/vikram-tamil-poster.png",
    year: "2022",
    rating: "R",
    genre: ["Action", "Crime", "Thriller"],
    duration: "174m",
    category: "tamil",
    videoSrc: "https://www.youtube.com/embed/OKBMCL-frPU",
    cast: ["Kamal Haasan", "Vijay Sethupathi", "Fahadh Faasil"],
    director: "Lokesh Kanagaraj",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 20,
    title: "Beast",
    description:
      "A RAW agent is in search of his captured team and the truth behind the assignment while dealing with terrorists who want to reveal the identity of the spy.",
    image: "/beast-tamil-poster.png",
    year: "2022",
    rating: "PG-13",
    genre: ["Action", "Comedy", "Thriller"],
    duration: "155m",
    category: "tamil",
    videoSrc: "https://www.youtube.com/embed/xZQR6Z1TElY",
    cast: ["Vijay", "Pooja Hegde", "Selvaraghavan"],
    director: "Nelson Dilipkumar",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 21,
    title: "Master",
    description:
      "An alcoholic professor is sent to a juvenile school, where he clashes with a gangster who uses the school children for criminal activities.",
    image: "/master-tamil-poster.png",
    year: "2021",
    rating: "R",
    genre: ["Action", "Crime", "Thriller"],
    duration: "179m",
    category: "tamil",
    videoSrc: "https://www.youtube.com/embed/UTiXQcrLlv4",
    cast: ["Vijay", "Vijay Sethupathi", "Malavika Mohanan"],
    director: "Lokesh Kanagaraj",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 22,
    title: "KGF Chapter 2",
    description:
      "The blood-soaked land of Kolar Gold Fields has a new overlord now - Rocky, whose name strikes fear in the heart of his foes.",
    image: "/kgf-chapter-2-poster.png",
    year: "2022",
    rating: "R",
    genre: ["Action", "Crime", "Drama"],
    duration: "168m",
    category: "tamil",
    videoSrc: "https://www.youtube.com/embed/JKa05nyUmuQ",
    cast: ["Yash", "Sanjay Dutt", "Raveena Tandon"],
    director: "Prashanth Neel",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 23,
    title: "Pushpa: The Rise",
    description:
      "A labourer rises through the ranks of a red sandalwood smuggling syndicate, making some powerful enemies in the process.",
    image: "/pushpa-tamil-poster.png",
    year: "2021",
    rating: "R",
    genre: ["Action", "Crime", "Drama"],
    duration: "179m",
    category: "tamil",
    videoSrc: "https://www.youtube.com/embed/pKctjlxbFDQ",
    cast: ["Allu Arjun", "Fahadh Faasil", "Rashmika Mandanna"],
    director: "Sukumar",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 24,
    title: "Sarkar",
    description:
      "An NRI businessman learns his vote has been cast by someone else and decides to investigate the matter, eventually finding himself pitted against two corrupt politicians.",
    image: "/sarkar-tamil-poster.png",
    year: "2018",
    rating: "PG-13",
    genre: ["Action", "Drama", "Thriller"],
    duration: "165m",
    category: "tamil",
    videoSrc: "https://www.youtube.com/embed/VkkyaodksT4",
    cast: ["Vijay", "Keerthy Suresh", "Varalaxmi Sarathkumar"],
    director: "A. R. Murugadoss",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 25,
    title: "Bigil",
    description: "A former football player struggles to train a women's football team and avenge his father's death.",
    image: "/bigil-tamil-poster.png",
    year: "2019",
    rating: "PG-13",
    genre: ["Action", "Drama", "Sport"],
    duration: "178m",
    category: "tamil",
    videoSrc: "https://www.youtube.com/embed/P663vdap0LM",
    cast: ["Vijay", "Nayanthara", "Jackie Shroff"],
    director: "Atlee",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 26,
    title: "Enthiran 2.0",
    description:
      "Dr. Vaseegaran creates Nila, a robot with the ability to understand human emotions and feelings. A mobile phone scientist and his team become a threat to the world.",
    image: "/2point0-tamil-poster.png",
    year: "2018",
    rating: "PG-13",
    genre: ["Action", "Drama", "Sci-Fi"],
    duration: "148m",
    category: "tamil",
    videoSrc: "https://www.youtube.com/embed/My9NyQNyFGE",
    cast: ["Rajinikanth", "Akshay Kumar", "Amy Jackson"],
    director: "Shankar",
    seasons: 1,
    episodes: 1,
  },
  {
    id: 27,
    title: "Asuran",
    description:
      "The teenage son of a farmer from an underprivileged caste kills a rich, upper caste landlord. How do the pacifist farmer and his hot-blooded son deal with the repercussions?",
    image: "/asuran-tamil-poster.png",
    year: "2019",
    rating: "R",
    genre: ["Action", "Drama", "Thriller"],
    duration: "141m",
    category: "tamil",
    videoSrc: "https://www.youtube.com/embed/TXABmWgKhEU",
    cast: ["Dhanush", "Manju Warrier", "Prakash Raj"],
    director: "Vetrimaaran",
    seasons: 1,
    episodes: 1,
  },
]

export async function GET(request: NextRequest, { params }: { params: { id: string } }) {
  try {
    const movieId = Number.parseInt(params.id)
    const movie = movies.find((m) => m.id === movieId)

    if (!movie) {
      return NextResponse.json({ success: false, error: "Movie not found" }, { status: 404 })
    }

    return NextResponse.json({
      success: true,
      data: movie,
    })
  } catch (error) {
    console.error("Error fetching movie:", error)
    return NextResponse.json({ success: false, error: "Failed to fetch movie" }, { status: 500 })
  }
}
